Fix HNS network removal error log level
A failure to remove an HNS network is a recoverable error, and should be
logged at debug level. This commit fixes an issue where this being
logged at info level.

log.V(1).Info needs to be used to log to debug level. log.V(1).Error
does not work. logger.Error has the documentation:
"The log message will always be emitted, regardless of verbosity level"